version: '3.7'

networks:
  minio-network:
    driver: bridge

services:
  minio:
    image: minio/minio:latest
    env_file:
      - .env
    volumes:
      - ./data:/data
    command: server /data --console-address ":9001"
    ports:
      - 9000:9000
      - 9001:9001
    networks:
      - minio-network
  localbucket:
    image: minio/mc:latest
    env_file:
      - .env
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "mc config host add --api s3v4 minio http://minio:9000 \$MINIO_ACCESS_KEY \$MINIO_SECRET_KEY; mc mb minio/\$MINIO_BUCKET_NAME/; mc anonymous set download minio/\$MINIO_BUCKET_NAME;"
    networks:
      - minio-network
  
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - minio
      - localbucket
    entrypoint: sh /app/entrypoint.sh
    networks:
      - minio-network
volumes:
  data: